package hello.utils;

public interface ReplyCodes {
    int USER_DELETED_SUCCESSFULLY = 1;
    int EMAIL_CONFIRMED_SUCCESSFULLY = 2;
    int TASK_DELETED_SUCCESSFULLY = 3;


    // REST OUT ERRORS
    int NOT_EXIST_ERROR = 100;
    int ALREADY_EXIST_ERROR = 101;
    int NOT_VALID_PARAMS_ERROR = 102;
    int NOT_DELETED_ERROR = 103;
    int UNKNOWN_ERROR = 104;

    // TOKEN
    int TOKEN_EXPIRED_ERROR = 200;
    int TOKEN_INVALID_ERROR = 201;

    // EMAIL
    int EMAIL_NOT_CONFIRMED_ERROR = 300;
    int EMAIL_OR_PASSWORD_ERROR = 301;
    int CANT_SEND_EMAIL_ERROR = 302;

    //////////////////////

    // IN SYSTEM ERRORS
    // USER
    int USER_NOT_EXIST_ERROR = -1;
    int USER_NOT_DELETED_ERROR = -2;
    int USER_ALREADY_EXIST_ERROR = -3;

    // TASK
    int NOT_VALID_PAGINATION_PARAMS_ERROR = -4;
    int TASK_NOT_EXIST_ERROR=-5;
    int TASK_NOT_DELETED_ERROR=-6;
    int CREATOR_USER_ID_NOT_EXIST_ERROR=-7;
    int RESPONSIBLE_USER_ID_NOT_EXIST_ERROR=-8;

}
