package hello.utils;

public interface ReplyCodes {
    int USER_DELETED_SUCCESSFULLY = 1;
    int EMAIL_CONFIRMED_SUCCESSFULLY = 2;
    int TASK_DELETED_SUCCESSFULLY = 3;

    // ERROR CODES
    // USER
    int USER_NOT_EXIST_ERROR = -1;
    int USER_NOT_DELETED_ERROR = -2;
    int USER_ALREADY_EXIST_ERROR = -3;
    int USER_EMAIL_NOT_EXIST_ERROR = -4;

    // TOKEN
    int TOKEN_EXPIRED_ERROR = -100;
    int TOKEN_INVALID_ERROR = -101;
    int TOKEN_UNKNOWN_ERROR = -102;


    // EMAIL
    int EMAIL_OR_PASSWORD_ERROR = -200;
    int EMAIL_NOT_CONFIRMED_ERROR = -201;

    // REGISTER
    int CANT_SEND_EMAIL_ERROR = -300;

    // TASK
    int NOT_VALID_PAGINATION_PARAMS_ERROR = -400;
   // int TASK_ALREADY_EXIST_ERROR=-401;
    int TASK_NOT_EXIST_ERROR=-401;
    int TASK_NOT_DELETED_ERROR=-402;
    int CREATOR_USER_ID_NOT_EXIST_ERROR=-403;
    int RESPONSIBLE_USER_ID_NOT_EXIST_ERROR=-404;

}
